# Generated by Django 4.2.1 on 2024-08-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resImage', models.URLField(max_length=1000, null=True)),
                ('resName', models.CharField(default='none', max_length=200)),
                ('estimated_time', models.CharField(default='30-40 min', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('locality', models.CharField(default='VijayNagar Indore', max_length=500)),
                ('offer', models.CharField(default='50% above ₹199', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='Unnamed Product', max_length=100)),
                ('price', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=200)),
                ('productImage', models.URLField(null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
        ),
    ]
