# Generated by Django 5.0.6 on 2024-06-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
