# Generated by Django 5.0.6 on 2024-06-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_alter_restaurants_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='category',
            new_name='menue',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='locality',
            field=models.CharField(default='VijayNagar Indore', max_length=500),
        ),
    ]
