# Generated by Django 5.0.6 on 2024-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0004_restaurants_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='offer',
            field=models.CharField(default='50% aboove ₹199', max_length=500),
        ),
    ]
