
version: '3'


services:
  db:
    image: postgres:16.3
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
    

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code  
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - redis

  # celery:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: celery -A learning worker -l info
  #   depends_on:
  #     - redis
  #   volumes:
  #     - .:/code
      
    
networks:
  default:
    driver: bridge
volumes:
  postgres_data:



