# Generated by Django 5.0.6 on 2024-07-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
